#!/usr/bin/env sh

sxhkd &

bspc monitor DP-2 -d I II III IV V
bspc monitor HDMI-1 -d VI VII VIII IX X

echo "it loaded the monitors"

 0: +DP-2 1920/476x1080/268+0+0  DP-2
 1: +HDMI-1 1920/477x1080/268+1920+0  HDMI-1

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
